### ISSUE TITLE
v1.0.0 - Remaining work

### ISSUE THREAD

**Issue by brendanhay** [brendanhay/amazonka#132]
This is a placeholder issue for the remaining work related to the updated generator in the `feature/ast` branch.

What was previously known only as the generator update - is now targeted as a `1.0.0` major release due to breaking changes to the surface APIs and the large number of fixes to outstanding tickets/issues.

- [x] Update to the 'new' botocore/AWS service definition structure + format.
- [x] #23 Migrate away from complicated hierarchical cabal sandboxes, to stack.
- [x] #109, #121 Configurable endpoints, timeouts and signing algorithms.
- [x]  #128 AWSPager granularity fixes.
- [x] #119 Prevent serialised response payloads being unwrapped too many times during deserialisation.
- [x] #105, #112, #113, #122, #135 Correct use of flattened vs unflattened list/map member serialisation.
- [x] #114 Correct serialisation of XML root elements.
- [x] #118 Ensure empty bodies are not sent in the absence of content for non-idempotent requests.
- [x] #101, #125 Correct deserialisation of XML/JSON error messages, even in the absence of content.
- [x] #98  Ensure the correct serialisation behaviour for empty vs optional collection types.
- [x] #130 Derive `Data`, `Typeable`, and `Generic` instances where appropriate/possible.
- [x] #24 Add strictness annotations for all types to avoid space-leaks.
- [x] #29 Remove need for intermediary elaborated/generated JSON models.
- [x] Simplify use of generator templates in favour of rendering Haskell AST using `haskell-src-exts`.
- [x] `Control.Monad.Trans.AWS` changes. (#104 for context.)
- [x] #22, #26 Updated Haddock documentation/usage for the exposed modules in `amazonka`.
- [x] Rework `amazonka` `Network.AWS.Internal.Body` helpers to use `streamFile` from `http-client`.
- [x] Bake invariants into `Base64` de/serialisation.
- [x] #127 Bake invariants into `ObjectKey` de/serialisation.
- [x] Obtain somewhat-emprical evidence that the field lens + sum constructor prefix changes are an improvement.
- [x] #9 Add additional request serialisation fixtures. (A couple per service would be a nice start.)
- [x] #9 Add additional response deserialisation fixtures. (As per above.)
- [x] #9 Add additional core de/serialisation tests.
- [x] Convince the entire project to build/test on travis-ci (Partially works, pending update to container-based builds, see: https://github.com/travis-ci/apt-source-whitelist/pull/7)
- [x] Convince the examples to build on travis-ci. (As above.)
- [x] #39 Add warning suppression for generated code where appropriate.

**Comment by brendanhay** [comment]
To any potential future employers - creating a monolithic feature branch and dumping 450~ unrealted commits into it is not usually how I work! :v:

**Comment by brendanhay** [comment]
This is basically all done. Remaining work revolves around ensuring regression tests/checks are done for signing and minor refactorings. Primarily the generator could use a lot of stylistic love, and additional fixtures and core serialisation tests should be added as ongoing work.

**Comment by brendanhay** [comment]
Also, no feedback was received about the prefix changes despite the lack of documentation/publicized reasoning behind the changes - so I figure everyone is A.O.K.
