### ISSUE TITLE
Release Checklist

### ISSUE THREAD

**Issue by endgame** [brendanhay/amazonka#857]
Consolidating chores here so I can move them to an issue template or something later.

- [x] Check for new regions
- [x] Update service bindings that have `Region -> Maybe Text` functions (usually returning an Account ID or Hosted Zone ID)
- [x] Update Botocore
- [x] Configure new services
- [x] Regenerate everything
- [x] Check against latest GHC versions
- [x] Add new IMDS paths to our client

**Comment by endgame** [comment]
@brendanhay This list of tasks is basically everything I want to do between 2.0 RC 2 and 2.0 final, and also capturing this list into an issue template.

**Comment by brendanhay** [comment]
Probably want to smooth out the "open a new issue" experience via a `.github/ISSUE_TEMPLATE/config.yaml`: https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository#configuring-the-template-chooser

**Comment by endgame** [comment]
IMDS Check in #935.

**Comment by endgame** [comment]
Successfully issued a `cabal test all`, building/testing the entire repo with GHC 8.10.7, 9.0.2, 9.2.8, 9.4.5, and 9.6.2 on `x86_64-pc-linux-gnu`. #936 makes the generator build against all these GHCs too.
